liquibase:
  enabled: true
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/dvit_db
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    username: postgres
    password: vitamind

micronaut:
  server:
    cors:
      enabled: true
  application:
    name: daily-sunny-vit-d-backend

openuv:
  header:
    token:
      name: x-access-token
      value: openuv-41mzrrlsrft745-io

google-elevation:
  api-key: AIzaSyDlnH9FbJv10OLiyWrBjtcByOmrZVBQXKk